export default function Head() {
  return (
    <>
      <title>Cedric Quitor</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta
        name="description"
        content="A portfolio website for Cedric Quitor"
      />
      <meta property="og:image" content="/images/preview.png" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
